#!/usr/bin/env python3
"""Build the example documents in this directory.

Every file here is generated by this script, so nothing is hand-edited and the
watermarks are exactly what the code says they are. Regenerate with::

    python examples/generate.py

Each example targets one detector. Upload the ``.txt`` files through
https://watermark-finder.pages.dev (Upload file) or paste their contents - both
paths preserve the hidden characters, unlike PDF.

Run ``python examples/generate.py --verify`` to analyse them locally with the
engine and print what each one should score.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENGINE = HERE.parent / "analysis-space"

# A neutral, assistant-register Polish paragraph. Using one base text for every
# example means the style score stays constant and only the covert channel
# changes, so each file isolates exactly one detector.
BASE = """Analiza nowoczesnych systemów autonomicznych wskazuje na kluczowe znaczenie \
zaawansowanych algorytmów uczenia maszynowego w optymalizacji procesów decyzyjnych. \
W kontekście współczesnej inżynierii, dynamiczny rozwój sieci neuronowych pozwala na \
bardziej precyzyjne przewidywanie wyników w złożonych środowiskach operacyjnych. \
Kluczowym wyzwaniem pozostaje jednak zapewnienie pełnej transparentności modeli, co \
jest niezbędne do budowania zaufania w interakcjach człowiek-maszyna.

Zastosowanie podejścia opartego na architekturze typu Mixture-of-Experts umożliwia \
znaczącą poprawę wydajności obliczeniowej przy jednoczesnym zachowaniu wysokiej \
jakości wyników. Dynamiczny charakter tych rozwiązań pozwala na efektywne \
skalowanie systemów w odpowiedzi na zmienne obciążenie. Kluczowe znaczenie ma \
również odpowiednia kalibracja parametrów, która bezpośrednio wpływa na stabilność \
całego procesu wnioskowania.

W kontekście praktycznych wdrożeń, podejście oparte na ciągłej walidacji wyników \
stanowi fundament niezawodności. Systemy autonomiczne wymagają stałego monitorowania \
kluczowych wskaźników wydajności, co umożliwia szybką reakcję na anomalie. \
Transparentność procesu decyzyjnego pozostaje kluczowym elementem budowania zaufania \
użytkowników do rozwiązań opartych na sztucznej inteligencji."""


def marker_watermark(text: str) -> str:
    """U+200B every ninth space, U+200D every fourteenth.

    A *marker* watermark: a fixed symbol at regular intervals. It identifies a
    document but carries no message, so the engine must report the watermark
    without inventing a payload.
    """
    out, spaces = [], 0
    for char in text:
        out.append(char)
        if char == " ":
            spaces += 1
            if spaces % 9 == 0:
                out.append("​")
            elif spaces % 14 == 0:
                out.append("‍")
    return "".join(out)


def tag_payload(text: str, message: str) -> str:
    """Append ``message`` encoded in Unicode tag characters (U+E0000 block).

    ``U+E0000 + n`` renders as nothing and maps to ASCII codepoint ``n``, so an
    arbitrary string can be stapled to a document invisibly. The engine decodes
    it back and quotes the recovered text.
    """
    return text + "".join(chr(0xE0000 + ord(c)) for c in message if 0x20 <= ord(c) <= 0x7E)


def variation_selector_payload(text: str, message: str) -> str:
    """Hide ``message`` as bytes in variation selectors, behind one character.

    Byte ``b`` becomes ``U+FE00 + b`` for ``b < 16``, else ``U+E0100 + b - 16``.
    A full 256-value alphabet, so any UTF-8 payload fits.
    """
    encoded = "".join(
        chr(0xFE00 + b) if b < 16 else chr(0xE0100 + b - 16) for b in message.encode("utf-8")
    )
    head, _, tail = text.partition(".")
    return f"{head}.{encoded}{tail}"


def homoglyph_swap(text: str) -> str:
    """Replace a few Latin letters with Cyrillic look-alikes.

    Invisible to a reader, survives reformatting far better than zero-width
    characters, and is the channel most likely to survive a copy-paste chain.
    """
    return (
        text.replace("systemów", "systеmów", 3)
        .replace("kluczowe", "kluczowе", 2)
        .replace("modeli", "mоdeli", 2)
    )


def zero_width_binary(text: str, message: str) -> str:
    """Encode ``message`` as bits: U+200B is 0, U+200C is 1, eight bits per byte.

    Unlike the marker example this really is a message, so the engine decodes it.
    """
    bits = "".join(f"{b:08b}" for b in message.encode("utf-8"))
    carrier = "".join("​" if bit == "0" else "‌" for bit in bits)
    return text + carrier


#: name -> (content, description, expected watermark label, expected payload)
#:
#: The expected values are asserted by ``--verify``, which CI runs, so the
#: results quoted in README.md cannot drift away from what the code does
#: without the build going red.
EXAMPLES: dict[str, tuple[str, str, str, str | None]] = {
    "01-clean.txt": (
        BASE,
        "No watermark at all. The control: proves the app does not cry wolf.",
        "clean",
        None,
    ),
    "02-marker-zero-width.txt": (
        marker_watermark(BASE),
        "Zero-width markers at regular intervals - a watermark with no message.",
        "watermark_detected",
        None,
    ),
    "03-payload-tag-characters.txt": (
        tag_payload(BASE, "owner:Mateusz|release:2026-08-13|id:WF-001"),
        "A readable message hidden in Unicode tag characters.",
        "payload_recovered",
        "owner:Mateusz|release:2026-08-13|id:WF-001",
    ),
    "04-payload-variation-selectors.txt": (
        variation_selector_payload(BASE, "leak-trace-42"),
        "A message hidden as bytes in variation selectors.",
        "payload_recovered",
        "leak-trace-42",
    ),
    "05-payload-zero-width-binary.txt": (
        zero_width_binary(BASE, "wm:demo-2026"),
        "A message encoded as binary in zero-width characters.",
        "payload_recovered",
        "wm:demo-2026",
    ),
    "06-homoglyphs.txt": (
        homoglyph_swap(BASE),
        "Cyrillic letters standing in for Latin ones inside Latin words.",
        "watermark_suspected",
        None,
    ),
}


def write_all() -> None:
    for name, (content, description, _label, _payload) in EXAMPLES.items():
        (HERE / name).write_text(content, encoding="utf-8")
        hidden = sum(1 for c in content if not c.isprintable() or 0xE0000 <= ord(c) <= 0xE01EF)
        cyrillic = sum(1 for c in content if 0x0400 <= ord(c) <= 0x04FF)
        print(
            f"{name:38s} {len(content):5d} chars  "
            f"hidden={hidden:3d} cyrillic={cyrillic:2d}  {description}"
        )


def verify() -> int:
    """Analyse every example with the local engine and print the verdicts."""
    sys.path.insert(0, str(ENGINE))
    try:
        from tpl.pipeline import analyse
    except ImportError:
        print(
            "The engine is not importable. Install it first:\n"
            "  cd analysis-space && pip install -r requirements.txt",
            file=sys.stderr,
        )
        return 1

    print(f"{'file':38s} {'watermark':>10s}  {'verdict':22s} {'style':>6s}  payload")
    print("-" * 100)
    failures = []
    for name, (_content, _description, expected_label, expected_payload) in EXAMPLES.items():
        result = analyse((HERE / name).read_text(encoding="utf-8"), "forensic")
        scores = result["scores"]
        payloads = [p["text"] for p in result["payloads"]]
        label = scores["watermark"]["label"]
        print(
            f"{name:38s} {scores['watermark']['value'] * 100:9.0f}%  "
            f"{label:22s} "
            f"{scores['llm_likelihood']['value'] * 100:5.0f}%  "
            f"{payloads or '-'}"
        )
        if label != expected_label:
            failures.append(f"{name}: expected verdict {expected_label!r}, got {label!r}")
        recovered = payloads[0] if payloads else None
        if recovered != expected_payload:
            failures.append(
                f"{name}: expected payload {expected_payload!r}, got {recovered!r}"
            )

    if failures:
        print("\nMISMATCH - the documented results no longer match behaviour:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1
    print("\nAll examples match their documented verdicts.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Analyse the examples with the local engine instead of writing them.",
    )
    args = parser.parse_args()
    if args.verify:
        return verify()
    write_all()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
