/**
 * A stand-in for the analysis Space.
 *
 * `installEngineStub` replaces `globalThis.fetch` with a handler that serves
 * the engine's contract, so route tests exercise the real SpaceClient - retries,
 * timeouts, header handling - without a network.
 */

import type { AnalysisResult } from '@wf/shared';

export interface EngineStubOptions {
  /** Fail this many times before succeeding, to exercise retry logic. */
  failTimes?: number;
  /** Status returned while failing. */
  failStatus?: number;
  /** Reject at the transport level instead of returning a status. */
  networkError?: boolean;
  /** Override the analysis result. */
  result?: Partial<AnalysisResult>;
  /** Text returned by /extract. */
  extractText?: string;
  healthy?: boolean;
}

export interface EngineStub {
  calls: { path: string; method: string; body?: unknown }[];
  restore: () => void;
  options: EngineStubOptions;
}

export function makeResult(overrides: Partial<AnalysisResult> = {}): AnalysisResult {
  const base: AnalysisResult = {
    schema_version: '1.0',
    engine: {
      name: 'text-provenance-lab',
      version: '1.0.0',
      mode: 'forensic',
      style_model: 'prior-logistic-v1',
      style_model_trained: false,
    },
    input: {
      chars: 512,
      words: 96,
      sentences: 7,
      paragraphs: 2,
      language: 'en',
      scripts: { LATIN: 420 },
      sha256: 'a'.repeat(64),
    },
    scores: {
      llm_likelihood: {
        value: 0.72,
        low: 0.58,
        high: 0.86,
        label: 'likely_ai',
        confidence: 'medium',
        model_id: 'prior-logistic-v1',
        trained: false,
        contributions: [
          {
            feature: 'sentence_length_cv',
            value: 0.31,
            z: -1.3,
            contribution: 0.5,
            direction: 'assistant',
            rationale: 'Uniform sentence length.',
          },
        ],
        notes: ['Coefficients are a documented prior.'],
      },
      watermark: { value: 0.97, label: 'payload_recovered', confidence: 'high', basis: 'bytes' },
      risk: { value: 0.93, label: 'critical' },
    },
    signals: [
      {
        id: 'payload_tag_characters',
        category: 'covert_channel',
        title: 'Hidden payload decoded from tag characters',
        description: 'Recovered 9 bytes.',
        score: 0.97,
        weight: 1,
        severity: 'critical',
        evidence: [{ kind: 'payload', detail: 'wm:demo-1', offset: null, length: 1 }],
        evidence_total: 1,
      },
    ],
    payloads: [
      {
        channel: 'tag_characters',
        text: 'wm:demo-1',
        byte_length: 9,
        printable_ratio: 1,
        carrier_count: 9,
        first_offset: 31,
        last_offset: 39,
        note: 'Unicode tag block',
      },
    ],
    segments: [
      {
        index: 0,
        start: 0,
        end: 256,
        word_count: 48,
        preview: 'First half of the document',
        llm_likelihood: 0.7,
        label: 'leaning_assistant',
        watermark_hits: 9,
      },
      {
        index: 1,
        start: 256,
        end: 512,
        word_count: 48,
        preview: 'Second half of the document',
        llm_likelihood: 0.4,
        label: 'mixed',
        watermark_hits: 0,
      },
    ],
    style_profiles: { disclaimer: 'Stylistic resemblance only.', matches: [] },
    features: { values: { mattr: 0.71 }, docs: { mattr: 'Lexical diversity.' } },
    perplexity: { available: false, reason: 'not requested' },
    findings: [
      {
        id: 'payload-tag_characters',
        severity: 'critical',
        title: 'Hidden message recovered',
        detail: 'Decoded content: wm:demo-1',
        recommendation: 'Strip the carrier characters.',
      },
    ],
    technical_report_markdown: '# Text provenance report\n\nGenerated by the stub engine.',
    warnings: [],
    timings_ms: { total: 12.5 },
    model_metrics: {},
  };
  return { ...base, ...overrides };
}

export function installEngineStub(options: EngineStubOptions = {}): EngineStub {
  const original = globalThis.fetch;
  const stub: EngineStub = { calls: [], restore: () => {}, options };
  let failures = 0;

  globalThis.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = new URL(typeof input === 'string' ? input : input.toString());
    const method = init?.method ?? 'GET';
    stub.calls.push({ path: url.pathname, method });

    if (url.pathname === '/health') {
      return options.healthy === false
        ? new Response('down', { status: 503 })
        : Response.json({ status: 'ok', version: '1.0.0' });
    }

    if (url.pathname === '/capabilities') {
      return Response.json({
        modes: ['quick', 'forensic'],
        max_chars: 200000,
        max_upload_bytes: 10485760,
        perplexity_enabled: false,
        supported_uploads: ['.txt', '.pdf', '.docx'],
        auth_required: true,
      });
    }

    if (failures < (options.failTimes ?? 0)) {
      failures += 1;
      if (options.networkError) throw new TypeError('network failure');
      return new Response('engine busy', { status: options.failStatus ?? 503 });
    }

    if (url.pathname === '/extract') {
      return Response.json({
        request_id: 'stub',
        text: options.extractText ?? 'Extracted text from the uploaded document.',
        format: 'pdf',
        pages: 2,
        truncated: false,
        notes: [],
        chars: (options.extractText ?? 'Extracted text from the uploaded document.').length,
      });
    }

    if (url.pathname === '/sanitize') {
      const body = init?.body ? JSON.parse(String(init.body)) : {};
      stub.calls[stub.calls.length - 1]!.body = body;
      const text = String(body.text ?? '');
      // Mirror the engine closely enough to be useful: drop tag characters,
      // count what went, and leave everything else alone.
      const cleaned = [...text].filter((ch) => {
        const cp = ch.codePointAt(0)!;
        return !(cp >= 0xe0000 && cp <= 0xe007f);
      }).join('');
      const removedTotal = [...text].length - [...cleaned].length;
      return Response.json({
        request_id: 'stub',
        text: cleaned,
        level: body.level ?? 'safe',
        changed: removedTotal > 0,
        removed: [],
        removed_total: removedTotal,
        replaced: [],
        replaced_total: 0,
        preserved: [],
        preserved_total: 0,
        warnings: [],
      });
    }

    if (url.pathname === '/mark') {
      const body = init?.body ? JSON.parse(String(init.body)) : {};
      stub.calls[stub.calls.length - 1]!.body = body;
      const recipients: string[] = body.recipients ?? [];
      const template: string = body.template ?? '{recipient}';
      return Response.json({
        request_id: 'stub',
        channel: body.channel ?? 'tag_characters',
        copies: recipients.map((recipient, i) => {
          const payload = template
            .replace('{recipient}', recipient)
            .replace(/\{index[^}]*\}/, String(i + 1));
          const carrier = [...payload]
            .map((ch) => String.fromCodePoint(0xe0000 + ch.charCodeAt(0)))
            .join('');
          return {
            recipient,
            payload,
            text: `${body.text}${carrier}`,
            channel: body.channel ?? 'tag_characters',
            carrier_chars: [...carrier].length,
            copies_embedded: body.repeat ?? 2,
            verified: true,
          };
        }),
        warnings: ['Exporting to PDF destroys the mark.'],
      });
    }

    if (url.pathname === '/analyze') {
      const body = init?.body ? JSON.parse(String(init.body)) : {};
      stub.calls[stub.calls.length - 1]!.body = body;
      return Response.json({
        request_id: 'stub',
        client_reference: body.client_reference ?? null,
        result: makeResult({
          ...options.result,
          engine: {
            ...makeResult().engine,
            mode: body.mode ?? 'forensic',
            ...(options.result?.engine ?? {}),
          },
        }),
      });
    }

    return new Response('not found', { status: 404 });
  }) as typeof fetch;

  stub.restore = () => {
    globalThis.fetch = original;
  };
  return stub;
}
